import Head from "next/head";
import Image from "next/image";

import ThemeSwitch from "@/components/ThemeSwitch";

export default function Home() {
    return (
        <div className="dark:bg-gray-900 relative overflow-hidden bg-white">
            <Head>
                <title>Create Next App</title>
                <meta
                    name="description"
                    content="Generated by create next app"
                />
                <link rel="icon" href="/favicon.ico" />
            </Head>
            <div className="max-w-7xl mx-auto">
                <main className="max-w-7xl sm:mt-12 sm:px-6 md:mt-16 lg:mt-20 lg:px-8 xl:mt-28 px-4 mx-auto mt-10">
                    <div className="sm:text-center lg:text-left">
                        <h1 className="sm:text-5xl md:text-6xl text-4xl font-extrabold tracking-tight text-gray-900">
                            <span className="xl:inline dark:text-gray-100 block">
                                NextJS, Tailwind, Typescript
                            </span>{" "}
                            <span className="xl:inline block text-blue-600">
                                starter
                            </span>
                        </h1>
                        <p className="sm:mt-5 sm:text-lg sm:max-w-xl sm:mx-auto md:mt-5 md:text-xl lg:mx-0 mt-3 text-base text-gray-500">
                            Anim aute id magna aliqua ad ad non deserunt sunt.
                            Qui irure qui lorem cupidatat commodo. Elit sunt
                            amet fugiat veniam occaecat fugiat aliqua.
                        </p>
                        <div className="sm:mt-8 sm:flex sm:justify-center lg:justify-start mt-5">
                            <div className="rounded-md shadow">
                                <a
                                    href="#"
                                    className="hover:bg-blue-700 md:py-4 md:text-lg md:px-10 flex items-center justify-center w-full px-8 py-3 text-base font-medium text-white bg-blue-600 border border-transparent rounded-md"
                                >
                                    Get started
                                </a>
                            </div>
                            <div className="sm:mt-0 sm:ml-3 mt-3">
                                <a
                                    href="#"
                                    className="hover:bg-blue-200 md:py-4 md:text-lg md:px-10 flex items-center justify-center w-full px-8 py-3 text-base font-medium text-blue-700 bg-blue-100 border border-transparent rounded-md"
                                >
                                    Live demo
                                </a>
                            </div>
                        </div>
                    </div>
                </main>

                <footer className="text-right">
                    <a
                        href="https://vercel.com?utm_source=create-next-app&utm_medium=default-template&utm_campaign=create-next-app"
                        target="_blank"
                        rel="noopener noreferrer"
                    >
                        Powered by{" "}
                        <span className="">
                            <Image
                                src="/vercel.svg"
                                alt="Vercel Logo"
                                width={72}
                                height={16}
                            />
                        </span>
                    </a>
                </footer>
            </div>
        </div>
    );
}
